dir:
	gcc -Wall -o main find_dir.c
	./main ../../ mtime + 7 -1
	./main ../../ mtime + 7 1
	./main ../../ atime - 3 2
nftw:
	gcc -Wall -o main find_nftw.c
	./main ../../ mtime + 7 -1
	./main ../../ mtime + 7 1
	./main ../../ atime - 3 2